---
abstract: 'Cached resolver for DBIx::DSN::Resolver'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-DSN-Resolver-Cached
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Cache::Memory::Simple: 0
  DBIx::DSN::Resolver: 0
  parent: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/DBIx-DSN-Resolver-Cached.git
version: 0.01
